### ISSUE TITLE
 run-biol-exmaples/mccbn-process.R with newer versions of MC-CBN

### ISSUE THREAD

**Issue by PabloHNieto** [rdiaz02/what_genotype_next#1]
Hello,

I'm having a problem while running MCCBN on the biological examples

In particular with the function `mccbn_proc`: 
```R
mccbn_proc <- function(x) {
   ...
    ## of course, lambda is per child
    lambda <- fit$fits[[mle_index]]$par #<-- But there is no $par, just $lambda and $llhodd
    names(lambda) <- colnames(am)
    dfr$lambda <- lambda[dfr$To]
    return(list(edges = dfr))
}
```
`lambda <- fit$fits[[mle_index]]$par` assigns `NULL`  to `lambda` and exits with an error.
Replacing `lambda <- fit$fits[[mle_index]]$par` to ` lambda <- fit$fits[[mle_index]]$lambda` seems to work. 
But I'm not sure if this is correct 

Pablo

**Comment by rdiaz02** [comment]
Thanks for the report and the suggested change. You are right. 

Short answer
============

- If using a version of MC-CBN from 7 October 2020, or later, I think you need  to make the change you suggest. In function `mccbn_proc` replace

```
lambda <- fit$fits[[mle_index]]$par
```
by
```
lambda <- fit$fits[[mle_index]]$lambda
```

I've changed the code so that by default it works with the newer version of MC-CBN and added a comment to make it explicit. 

Details 
========

- MC-CBN was updated (on GitHub) on 2017-03-24 and the next commit available in GitHub is from 2020-10-07. All our analyses were conducted before 2020-10-07 (between 2018 and early summer 2020). As we indicate in the supplementary material,

> "MCCBN was run using version 1.1.9 of the mccbn package,  downloaded from github (https://github.com/cbg-ethz/MC-CBN on January 2018, which had been last updated on 2017-03-24)."

That was the last version available up to early summer of 2020.


- On 7-October-2020 many changes are reflected on GitHub, and several indicate that, yes, you should use $lambda instead of $par.


  - The changes in the code itself I think were introduced in commit f497c67eefc9c0bdf188466613dce8b9df9cc54b :  https://github.com/cbg-ethz/MC-CBN/commit/f497c67eefc9c0bdf188466613dce8b9df9cc54b

   - In particular:
     -  In `src/mcem.cpp`:
          - Function `_MCEM` returns a list, with component "lambda" .  The return value from _MCEM is assigned to "res" which is             what is now  returned by `MCEM`. (Instead of having `MCEM` return a List with a named  component "par", which is what happened previously)

     - Note also that in `R/mcem_network_learning.r`:
        - Function `genotype_probs_empty_poset` now uses "fit$lambda" instead of  "fit$par". This is a function that uses the returned object from a call to MCEM

     - We call, in the code you show, the function `learn_network`. This function  is defined in `R/mcem_network_learning.r`. It calls `learn_network_internal`,  which itself calls MCEM. learn_network returns a list, with one of its  components called "fits" (line 182). This "fits" component is itself a list of,  well, fits (line 171), each one of them the result of that call to MCEM (line 146).

       In our code, we access the "$par" component of one of those fits (`lambda <- fit$fits[[mle_index]]$par`).  But now, as explained above, that "$par" is called "$lambda", as MCEM now returns "$lambda"

       
   - Additionally, note that in commit
     https://github.com/cbg-ethz/MC-CBN/commit/41d7b29a787611ba53b4a24c8e14cf3a3ed4da34, 
     which affects the README.md file, the authors are using$lambda instead of $par for comparing errors of estimates (see        est_lambda$lambda, which used to be est_lambda$par)
